# Generated by Django 3.2.7 on 2021-09-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaCallBacks',
        ),
    ]
