# Generated by Django 3.2.7 on 2021-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=50, null=True)),
                ('accountNumber', models.CharField(max_length=50, null=True)),
                ('transaction', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Account',
            },
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('retryCount', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('networkCode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Delivery Report',
                'verbose_name_plural': 'Delivery Reports',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('to', models.IntegerField()),
                ('linkId', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Inbox',
                'verbose_name_plural': 'Inbox',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('statusCode', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('text', models.CharField(max_length=255)),
                ('messageId', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Outbox',
                'verbose_name_plural': 'Outbox',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('kin_name', models.CharField(max_length=100, null=True)),
                ('id_number', models.IntegerField(null=True)),
                ('kin_id_number', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('kin_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('kin_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('house_number', models.CharField(max_length=50, null=True)),
                ('account_number', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
