# Generated by Django 3.2.7 on 2021-11-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='profile',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_name', to='apex.profile'),
        ),
    ]
