# Generated by Django 3.2.7 on 2021-10-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
