# Generated by Django 3.2.7 on 2021-09-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
