# Generated by Django 3.2.7 on 2021-11-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['invoice_number']},
        ),
    ]
