# Generated by Django 4.1.4 on 2022-12-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_alter_invoice_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='profile',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.profile'),
        ),
    ]
