# Generated by Django 3.2.7 on 2021-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
