# Generated by Django 3.2.7 on 2021-09-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_alter_feedback_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
