# Generated by Django 3.2.7 on 2021-10-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_auto_20211027_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
