# Generated by Django 3.2.7 on 2021-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_auto_20211028_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
    ]
