# Generated by Django 3.2.7 on 2021-11-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0003_houses_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='residence',
        ),
    ]
