# Generated by Django 3.2.7 on 2021-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0003_nextofkin_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='relationship',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
