# Generated by Django 3.2.7 on 2021-11-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0004_alter_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
