# Generated by Django 3.2.7 on 2021-10-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0004_nextofkin_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='email',
            new_name='kin_email',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='id_number',
            new_name='kin_id_number',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='name',
            new_name='kin_name',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='phone_number',
            new_name='kin_phone_number',
        ),
    ]
