# Generated by Django 3.2.7 on 2021-10-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0005_auto_20211029_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='house_number',
            new_name='kin_house_number',
        ),
    ]
