# Generated by Django 3.2.7 on 2021-11-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0005_invoice_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='house_number',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='name',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
