# Generated by Django 3.2.7 on 2021-11-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0006_auto_20211124_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
