# Generated by Django 3.2.7 on 2021-10-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0006_rename_house_number_nextofkin_kin_house_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextOfKin',
        ),
        migrations.AddField(
            model_name='profile',
            name='Kin_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kin_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kin_id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kin_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
