# Generated by Django 3.2.7 on 2021-10-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0007_auto_20211029_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Kin_name',
            new_name='kin_name',
        ),
    ]
