# Generated by Django 3.2.7 on 2021-10-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0008_rename_kin_name_profile_kin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
